# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black
      args: [--config, pyproject.toml]
#-   repo: https://github.com/pycqa/isort
#    rev: 5.6.4
#    hooks:
#    - id: isort
#      args: [--settings-path, pyproject.toml]
