from dataclasses import dataclass, replace
from decimal import Decimal
from math import sin, cos
from typing import Type, Mapping

from dg_commons import logger

import numpy as np
from frozendict import frozendict
from geometry import SE2value, SE2_from_xytheta, SO2_from_angle, SO2value, T2value
from scipy.integrate import solve_ivp
from shapely.geometry import Polygon

from dg_commons import apply_SE2_to_shapely_geo
from dg_commons.sim import ImpactLocation, IMPACT_EVERYWHERE
from dg_commons.sim.models import ModelType, ModelParameters
from dg_commons.sim.models.model_utils import apply_force_limits, apply_full_ang_vel_limits  # , apply_speed_limits
from dg_commons.sim.models.satellite_structures import SatelliteGeometry, SatelliteParameters
from dg_commons.sim.simulator_structures import SimModel


@dataclass(unsafe_hash=True, eq=True, order=True)
class SatelliteCommands:
    F_left: float
    """ Thrust generated by left engine [N]"""
    F_right: float
    """ Thrust generated by right engine [N]"""

    idx = frozendict({"F_left": 0, "F_right": 1})
    """ Dictionary to get correct values from numpy arrays"""

    @classmethod
    def get_n_commands(cls) -> int:
        return len(cls.idx)

    def __add__(self, other: "SatelliteCommands") -> "SatelliteCommands":
        if type(other) == type(self):
            return replace(
                self,
                F_left=self.F_left + other.F_left,
                F_right=self.F_right + other.F_right,
            )
        else:
            raise NotImplementedError

    __radd__ = __add__

    def __sub__(self, other: "SatelliteCommands") -> "SatelliteCommands":
        return self + (other * -1.0)

    def __mul__(self, val: float) -> "SatelliteCommands":
        return replace(self, F_left=self.F_left * val, F_right=self.F_right * val)

    __rmul__ = __mul__

    def __truediv__(self, val: float) -> "SatelliteCommands":
        return self * (1 / val)

    def as_ndarray(self) -> np.ndarray:
        return np.array([self.F_left, self.F_right])

    @classmethod
    def from_array(cls, z: np.ndarray):
        assert cls.get_n_commands() == z.size == z.shape[0], f"z vector {z} cannot initialize VehicleInputs."
        return SatelliteCommands(F_left=z[cls.idx["F_left"]], F_right=z[cls.idx["F_right"]])


@dataclass(unsafe_hash=True, eq=True, order=True)
class SatelliteState:
    x: float
    """ CoG x location [m] """
    y: float
    """ CoG y location [m] """
    psi: float
    """ Heading (yaw) [rad] """
    vx: float
    """ CoG longitudinal velocity [m/s] """
    vy: float
    """ CoG longitudinal velocity [m/s] """
    dpsi: float
    """ Heading (yaw) rate [rad/s] """
    idx = frozendict({"x": 0, "y": 1, "psi": 2, "vx": 3, "vy": 4, "dpsi": 5})
    """ Dictionary to get correct values from numpy arrays"""

    @classmethod
    def get_n_states(cls) -> int:
        return len(cls.idx)

    def __add__(self, other: "SatelliteState") -> "SatelliteState":
        if type(other) == type(self):
            return replace(
                self,
                x=self.x + other.x,
                y=self.y + other.y,
                psi=self.psi + other.psi,
                vx=self.vx + other.vx,
                vy=self.vy + other.vy,
                dpsi=self.dpsi + other.dpsi,
            )
        else:
            raise NotImplementedError

    __radd__ = __add__

    def __sub__(self, other: "SatelliteState") -> "SatelliteState":
        return self + (other * -1.0)

    def __mul__(self, val: float) -> "SatelliteState":
        return replace(
            self,
            x=self.x * val,
            y=self.y * val,
            psi=self.psi * val,
            vx=self.vx * val,
            vy=self.vy * val,
            dpsi=self.dpsi * val,
        )

    __rmul__ = __mul__

    def __truediv__(self, val: float) -> "SatelliteState":
        return self * (1 / val)

    def __repr__(self) -> str:
        return str({k: round(float(v), 2) for k, v in self.__dict__.items() if not k.startswith("idx")})

    def as_ndarray(self) -> np.ndarray:
        return np.array([self.x, self.y, self.psi, self.vx, self.vy, self.dpsi])

    @classmethod
    def from_array(cls, z: np.ndarray):
        assert cls.get_n_states() == z.size == z.shape[0], f"z vector {z} cannot initialize SatelliteState."
        return SatelliteState(
            x=z[cls.idx["x"]],
            y=z[cls.idx["y"]],
            psi=z[cls.idx["psi"]],
            vx=z[cls.idx["vx"]],
            vy=z[cls.idx["vy"]],
            dpsi=z[cls.idx["dpsi"]],
        )


class SatelliteModel(SimModel[SatelliteState, SatelliteCommands]):
    def __init__(self, x0: SatelliteState, rg: SatelliteGeometry, rp: SatelliteParameters):
        self._state: SatelliteState = x0
        """ Current state of the model"""
        self.XT: Type[SatelliteState] = type(x0)
        """ State type"""
        self.rg: SatelliteGeometry = rg
        """ The vehicle's geometry parameters"""
        self.rp: SatelliteParameters = rp
        """ The vehicle parameters"""

    @classmethod
    def default(cls, x0: SatelliteState):
        return SatelliteModel(x0=x0, rg=SatelliteGeometry.default(), rp=SatelliteParameters.default())

    def update(self, commands: SatelliteCommands, dt: Decimal):
        """
        Perform initial value problem integration
        to propagate state using actions for time dt
        """

        def _stateactions_from_array(y: np.ndarray) -> [SatelliteState, SatelliteCommands]:
            n_states = self._state.get_n_states()
            state = self._state.from_array(y[0:n_states])
            if self.has_collided:
                actions = SatelliteCommands(F_left=0, F_right=0)
            else:
                actions = SatelliteCommands(
                    F_left=float(y[SatelliteCommands.idx["F_left"] + n_states]),
                    F_right=float(y[SatelliteCommands.idx["F_right"] + n_states]),
                )
            return state, actions

        def _dynamics(t, y):
            state0, actions = _stateactions_from_array(y=y)
            dx = self.dynamics(x0=state0, u=actions)
            du = np.zeros([len(SatelliteCommands.idx)])
            return np.concatenate([dx.as_ndarray(), du])

        state_np = self._state.as_ndarray()
        action_np = commands.as_ndarray()
        y0 = np.concatenate([state_np, action_np])
        result = solve_ivp(fun=_dynamics, t_span=(0.0, float(dt)), y0=y0)

        if not result.success:
            raise RuntimeError("Failed to integrate ivp!")
        new_state, _ = _stateactions_from_array(result.y[:, -1])
        self._state = new_state
        return

    def dynamics(self, x0: SatelliteState, u: SatelliteCommands) -> SatelliteState:
        """
        Returns state derivative for given control inputs
        Note that this model has velocities expressed in global frame!

        Dynamics:
        dx/dt = vx
        dy/dt = vy
        dψ/dt = vψ
        dvx = 1 / m * cos(ψ) * (F_lx + F_rx)
        dvy = 1 / m * sin(ψ) * (F_lx + F_rx)
        dvψ/dt = 1/I*l2*(F_r-F_l)
        """

        F_lx = apply_force_limits(u.F_left, self.rp.F_limits)
        F_rx = apply_force_limits(u.F_right, self.rp.F_limits)

        # set actions to zero if vehicle has no more fuel
        # if x0.m <= self.rp.m_v:
        #     F_lx = 0
        #     F_rx = 0
        #     logger.warning("Vehicle has no more fuel!")

        psi = x0.psi
        dpsi = x0.dpsi
        vx = x0.vx
        vy = x0.vy

        m = self.rp.m_v

        dx = vx
        dy = vy
        dvx = 1 / m * cos(psi) * (F_lx + F_rx)
        dvy = 1 / m * sin(psi) * (F_lx + F_rx)
        dvpsi = 1 / self.rg.Iz * self.rg.l_m * (F_rx - F_lx)

        return SatelliteState(x=dx, y=dy, psi=dpsi, vx=dvx, vy=dvy, dpsi=dvpsi)

    def get_footprint(self) -> Polygon:
        """Returns current footprint of the satellite (mainly for collision checking)"""
        footprint = self.rg.outline_as_polygon
        transform = self.get_pose()
        footprint: Polygon = apply_SE2_to_shapely_geo(footprint, transform)
        assert footprint.is_valid
        return footprint

    def get_mesh(self) -> Mapping[ImpactLocation, Polygon]:
        footprint = self.get_footprint()
        impact_locations: Mapping[ImpactLocation, Polygon] = {
            IMPACT_EVERYWHERE: footprint,
        }
        for shape in impact_locations.values():
            assert shape.is_valid
        return impact_locations

    def get_pose(self) -> SE2value:
        return SE2_from_xytheta([self._state.x, self._state.y, self._state.psi])

    @property
    def model_geometry(self) -> SatelliteGeometry:
        return self.rg

    def get_velocity(self, in_model_frame: bool) -> (T2value, float):
        vx = self._state.vx
        vy = self._state.vy
        dpsi = self._state.dpsi
        v_l = np.array([vx, vy])

        if not in_model_frame: # asked as global
            return v_l, dpsi # dynamics in global frame

        # else transfor global to local
        rot: SO2value = SO2_from_angle(-self._state.psi)
        v_g = rot @ v_l
        return v_g, dpsi

    def set_velocity(self, vel: T2value, dpsi: float, in_model_frame: bool):
        if in_model_frame: # provided in body frame
            # local to global
            rot: SO2value = SO2_from_angle(self._state.psi)
            vel = rot @ vel

        # else already in global frame
        self._state.vx = vel[0]
        self._state.vy = vel[1]
        self._state.dpsi = dpsi

    @property
    def model_type(self) -> ModelType:
        return self.rg.model_type

    @property
    def model_params(self) -> ModelParameters:
        return self.rp

    def get_extra_collision_friction_acc(self):
        # this model is not dynamic
        pass
